# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200

checkpoint:
  no_epoch_checkpoints: true
  best_checkpoint_metric: wer
  save_interval: 20
  save_interval_updates: 25000
  keep_interval_updates: 1

task:
  _name: audio_finetuning
  data: ???
  normalize: false
  labels: ltr

dataset:
  num_workers: 6
  max_tokens: 1400000
  required_batch_size_multiple: 8
  required_seq_len_multiple: 1
  skip_invalid_size_inputs_valid_test: true
  valid_subset: dev
  validate_interval: 20
  validate_interval_updates: 0
  validate_after_updates: 0

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 8

criterion:
  _name: ctc
  zero_infinity: true
  sentence_avg: false

optimization:
  max_update: 50000
  lr: [0.0001]
  update_freq: [4]
  clip_norm: 0.0
  sentence_avg: false

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  init_lr_scale: 0.01
  final_lr_scale: 0.1

model:
  _name: wav2vec_ctc
  w2v_path: ???
  apply_mask: true
  mask_prob: 0.65
  mask_channel_prob: 0.5
  mask_channel_length: 64
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 25000
  normalize: false

